### ISSUE TITLE
[Feature] export to doc/docx format

### ISSUE THREAD

**Issue by abdelrahmanahmed** [AmruthPillai/Reactive-Resume#104]
I have some manual modification which i need modify in the CV , like adding companies logo. exporting CV to `.docx` format would be a nice feature to have.

**Comment by AmruthPillai** [comment]
I have looked into this earlier, and I'm afraid it's not that simple. Since DOC/DOCX are proprietary formats from Microsoft, there isn't that much research that goes into converting HTML to DOCX properly. The libraries that do exist now, they don't work well with lots of colors/images/objects.

One suggestion that might work for you to make further changes, is to print your resume (using the browser print functionality) as a PDF and use a software like PDFElement to edit your PDF and give it the finishing touches you need.
