### ISSUE TITLE
[Bug] PDF export

### ISSUE THREAD

**Issue by Ciboulette** [AmruthPillai/Reactive-Resume#106]
**Describe the Bug**
The PDF export is not working anymore
**Reproduction**
Steps to reproduce the behaviour:
1. Go to the website
2. Fill mutliple fields
3. Click export PDF button
4. The downloaded pdf is a blank page

**Expected Behaviour**

It should show the content I filled

**Screenshots**

**Desktop (please complete the following information):**
MacOS / Chrome

**Additional Context**

**Comment by AmruthPillai** [comment]
Hey there, this issue seems serious. Are you able to pinpoint as to what is actually causing this? I just tried it now on my system macOS Chrome and Android Chrome, the Download PDF functionality works as expected, all types (Unconstrained, Fit in A4 and Multi-Page A4).

Could you give me some more insight into what data you are entering? Also, have you tried clearing your cache and refreshing (Shift + Cmd + R on macOS Chrome)?

**Comment by Ciboulette** [comment]
Seems good now.
