### ISSUE TITLE
[BUG] Date of Birth is not the same when rendered

### ISSUE THREAD

**Issue by TheJordanDev** [AmruthPillai/Reactive-Resume#1061]
**Describe the bug**

**Product Flavor**

- [X] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

When I enter my birth date the preview is fine but when downloading the PDF the date is one day before.
<i>I'm in France if it helps</i>

**Expected behavior**

The date should be the same as when entered in the "Date of Birth" input

**Screenshots**

![image](https://user-images.githubusercontent.com/55529456/198365790-8e3b820d-e511-4ac8-a660-4f4c02432e7e.png)

**Desktop (please complete the following information):**

- OS: 
- Browser 
- Version 

**Additional context**

**Comment by AreYouLoco** [comment]
Is this something that can be worked on?

**Comment by AmruthPillai** [comment]
@AreYouLoco It definitely is in my top priority to fix this, whenever I get the time to update the project. I have made some attempts at fixing this issue in the past, but looks like none of them panned out.

My only alternative solution is to store dates as strings on the server and then it would get printed as-is instead of having to deduce the timezone. It's a bit of a tricky step as I wouldn't want to break any existing resumes, so requires some more thought. But it definitely should be fixed soon. Thank you for bringing this up, and thank you for continuing to use Reactive Resume despite its shortcomings :)

**Comment by AreYouLoco** [comment]
I asked my brother to take a look as well. He is a JS (react) programmer.

**Comment by Anish-Shobith** [comment]
Can encounter the same issue here
