### ISSUE TITLE
[BUG] Auto Page breaker once A4 size of page is reached

### ISSUE THREAD

**Issue by yashsawarkar** [AmruthPillai/Reactive-Resume#1079]
A4 size page is not breaking/split the content on the next page, 
ideally, it should throw the continued content into the next page automatically to avoid lot of blank spaces on resume,

**Comment by emielderckx** [comment]
I can confirm that when I export my CV it doesn't get split into multiple pages but only creates one long page.

Please notify me if someone knows a workaround :)

**Comment by turtaf** [comment]
Confirming this need...

I have too many projects that don't fit on a page.

Suggestion: allow to duplicate the project section (in my case, of course, other sections in other cases) into two separate ones, then put the one per page. 
Possible Drawback: I don't know whether it will be feasible  to move items between the sections and pages easily

**Comment by rdhubcity** [comment]
can you please provide me the reference for those projects, the duplication will not actually solve the gaping issue (Content size is small for some sections, and for some content size is big), and duplication of section is not an ideal solution..

**Comment by turtaf** [comment]
You can find my example cv here

https://rxresu.me/emanue/cv-202211-ita

The projects section gets the page longer than a normal A4.

Let me know if mor info is needed.

Cheers,
e.

**Comment by hemmanshu-sethh** [comment]
+1...having same problem

**Comment by maddy1104** [comment]
+1 - Facing the same issue. Could you look into it

**Comment by rdhubcity** [comment]
@turtaf that's just a another way around (tactical fix)

**Comment by AmruthPillai** [comment]
Hey folks,

This isn't really a bug because the intended effect is to overflow if necessary, and the user (editor) is in control of when to create new pages and to drag/drop layouts and sections into other pages. I never designed the app to auto break-up into multiple pages because honestly, that's just too complex of a problem to solve for myself.

So, this is more of a feature request than a bug. But since I do not have plans to work on a feature similar to this at the moment, will have to close this issue to avoid further confusion. Apologies if the instruction wasn't clear in how the app works, hoping to make the verbiage better.

**Comment by yashsawarkar** [comment]
@AmruthPillai no worrys, still has a nice interface (UI)

**Comment by aryanat1911** [comment]
@amruthpillai Are there any plans to implement auto break-up multiple pages?
