### ISSUE TITLE
[BUG] Docker Image to support ARM processor

### ISSUE THREAD

**Issue by kgotso** [AmruthPillai/Reactive-Resume#1091]
**Describe the bug**
Running any of the docker images on an ARM based processor results in a failure of the container to start up correct leading to a failed deployment with no way to resolve

**Product Flavor**
server and client

**To Reproduce**

Docker compose on ARM processor 

**Expected behavior**

Should behave as per usual 

**Screenshots**

None available 

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser Chrome N/A
- Version NA

**Additional context**

At the time, tested on Oracle Cloud ARM vps

**Comment by AmruthPillai** [comment]
The support from ARM is at a bottleneck right now due to upstream dependencies (Playwright). It has some issues with PDF generation on ARM and because of that, haven't able to focus on this a lot.

I'm actually considering removing the ARM package on Docker for the moment so as to not cause any more issues. And we can bring it back later once the upstream issues have been fixed.

** I am also looking for someone who's really experienced in Docker and GitHub Actions to help me clean up the whole CI/CD pipeline to make it more streamlined. So if anyone is interested, please hit me up!
