### ISSUE TITLE
The picture does not show on the downloaded pdf[BUG] 

### ISSUE THREAD

**Issue by apodracki** [AmruthPillai/Reactive-Resume#1129]
**Describe the bug**

**Product Flavor**

- [x] Managed (https://rxresu.me)
- [ ] Self Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Browser 
- Version 

**Additional context**

**Comment by keshavjha06** [comment]
@AmruthPillai Facing the same issue.Picture is not displaying in downloaded pdf

**Comment by keshavjha06** [comment]
@AmruthPillai  I'm getting this issue again.

**Comment by AmruthPillai** [comment]
@keshavjha06 Could you send me an email of the link to the resume so that I can check?

**Comment by keshavjha06** [comment]
@AmruthPillai I've just now figured it out about the issue. The issue is when I"m downloading directly from the rxresu.me website, the photo is not getting displayed but when copying the URL from Sharing section and pasting it in browser and then downloading the resume from there, the photo is displayed . You can try the same steps
