### ISSUE TITLE
[Bug] Bullet-formatting in a job description

### ISSUE THREAD

**Issue by KeronCyst** [AmruthPillai/Reactive-Resume#113]
**Describe the Bug**
Bullet-formatting is messed up for a certain chunk of text unless I put two line breaks, instead of one, between each bullet.

**Reproduction**
Steps to reproduce the behaviour:

1. In the "Description" field for a job in "Work," paste:

```
* Manage diverse varieties of classrooms on demand

* Follow organizational policy, adapting to unexpected situations

* Guide motivation & obedience of students of contrasting socioeconomic backgrounds
```

2. See error

**Expected Behaviour**
Text should look like: 
![image](https://user-images.githubusercontent.com/13827055/79498146-b5093180-7fdd-11ea-88e8-fc5f4e7ea51b.png)

**Actual Result**
![image](https://user-images.githubusercontent.com/13827055/79498215-c81c0180-7fdd-11ea-82d7-242a5afcd6d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome 80.0.3987.163 (apparently I needed an update)

**Additional Context**
Workaround: double the line breaks so there are two line breaks between bullets and it works fine.

**Comment by AmruthPillai** [comment]
This is expected behavior from Markdown. What it tries to do is fit the entire section of the text into one line, and that forces it to be pushed down. That's because line breaks are not generally necessary to divide the bullets, you can just jot them down as you go, like this:

```markdown
* Manage diverse varieties of classrooms on demand
* Follow organizational policy, adapting to unexpected situations
* Guide motivation & obedience of students of contrasting socio-economic backgrounds
```

This resulted in a design that is similar to what you wanted:
![image](https://user-images.githubusercontent.com/1134738/79540654-22809500-80a6-11ea-92d1-7ce1b26cbafb.png)
