### ISSUE TITLE
[BUG] Adresse in German is not in the correct order - is it configurable?

### ISSUE THREAD

**Issue by andywenk** [AmruthPillai/Reactive-Resume#1175]
I realised that I am not able to define the order for the address following the German standard. See the file attached. 

It is now: Street, City, Zip, Country

It should be: Street, ZIP City, Country 

P.S.: I am really impressed from Reactive Resume and I highly appreciate your work. I used it now for many days and it's awesome.

**Comment by AmruthPillai** [comment]
Would it be feasible to enter ZIP and City together in the City field, so that the comma wouldn't show up? And you can skip the actual Zip and State fields so they don't appear at all. 

It's a hack, I understand, but this level of configuration usually makes the UI more complex to use and that's something I'd like to avoid :)
