### ISSUE TITLE
Missing translation and problems with font [Bug] 

### ISSUE THREAD

**Issue by RazziaDK** [AmruthPillai/Reactive-Resume#119]
**Describe the Bug**
I found two issues:
- In some themes (Eg. Castform) things is not translated.  
In the left side of the page, the following is not translated: "Contact information", "Address", "Phone", "Email address". It appears to be the same for all languages.

- When exporting to PDF, the font changes.
When I export the resume to a PDF, the font changes to Times New Roman (I think it is Times New Roman). I tested online in the webapp, and it works there, but when I run it in Docker the issue with font appears.

**Reproduction**
Steps to reproduce the behaviour:
1. Run the latest version in Docker.
2. Write the resume.
3. Choose theme Castform.
4. Export.

**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/7606777/79699806-122d0d80-8292-11ea-8978-4ebd7d70ea85.png)

The docker version is seen on the left, and the PDF is on the right.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Hosting: Docker

**Comment by AmruthPillai** [comment]
Hey there!

This is a problem I've noticed. So the issue is Firefox has some trouble rendering the canvas is the font you've chosen has a space in the middle, like "Fira Sans" or "Open Sans". It's really weird, and I haven't found a fix for it yet, still looking into this.

As a quick hack, if you need to get your resume exported quickly, you can use the latest version of Google Chrome (or any Chromium browser, like Edge or Brave) with the same font. Or, if you would like to stick with Firefox, you would have to choose a font that doesn't have spaces in it.
