### ISSUE TITLE
[FEATURE] Single colum view for work experience

### ISSUE THREAD

**Issue by tom9865** [AmruthPillai/Reactive-Resume#1223]
Hi,

I was wondering if there is any chance to have the work experience overview displayed in one column? I have in every template always a two-column view.
Or did I miss any setting to adapt the template?

BR,
Tom

**Comment by AmruthPillai** [comment]
You should be able to find the option to change the number of columns, just below the section you want to change. As shown here in the screenshots below.

<img width="493" alt="Screenshot 2023-02-10 at 8 34 43 AM" src="https://user-images.githubusercontent.com/1134738/217990188-5142634c-7972-49fd-9914-ac5337df4627.png">
<img width="259" alt="Screenshot 2023-02-10 at 8 34 54 AM" src="https://user-images.githubusercontent.com/1134738/217990197-f115f967-3a7a-458f-b3d1-79ed77c4ae4f.png">

**Comment by JacobARose** [comment]
I believe this should be reopened!

I have an issue where even when I've set the Work Experience section to 1 column, most of the templates have a mandatory sidebar that seems to count as a kind of global 2nd column any way.

While I like having a sidebar for a skills section, what ends up happening is I have maybe 10 lines of skills in the sidebar, then like multiple pages of unused blank space because my work experience section requires much more detail.

I'd like the ability to use the full width of the page from some sections, while optionally segmenting smaller sections to maybe a 1-page or partial-page sidebar.
