### ISSUE TITLE
Loading a picture from the local drive 

### ISSUE THREAD

**Issue by khmohrprivat** [AmruthPillai/Reactive-Resume#124]
Hello Amruth, 
I would like to load the personal image from the local hard disk and not via http: //
it is possible to load a file from the local hard drive in the photo-url field. 
Unfortunately File: /// doesn't help me. Is there any solution to load it from my local drive C:

Thank you very much for Your support
Best regards 
Karl-Heinz

**Comment by AmruthPillai** [comment]
Hey there @khmohrprivat!

I have looked into this before, assuming it would've just been easier to load images locally instead of uploading them elsewhere, but sadly that is a security issue and has been disabled by most browsers inherently. Implementing something like that would mean you have to enable certain flags on your browser.

Here's a link related to this security issue, if you would like to know more:
https://stackoverflow.com/a/4090736/1248133
