### ISSUE TITLE
[Bug] Dates not displaying correctly

### ISSUE THREAD

**Issue by andy-vdg** [AmruthPillai/Reactive-Resume#1582]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

On my resume that I haven't touched in months everything broke. Including dates that are now all showing as:
2016-06-02T00:00:00.000Z
Maybe the V4 update broke this? It's an easy fix - edit date and remove everything after yyyy-mm-dd and it saves correctly again. 

### Expected Behavior

Dates should stay the same - ideally. 

### Steps To Reproduce

Create a Resume 
Publish it
Revisit after say 6 months
Realise everything is broken. 

### What template are you using?

None

**Comment by AmruthPillai** [comment]
This unfortunately cannot be fixed by myself, I can't really run any migrations on your resume data itself (for obvious security reasons).

I would suggest simply changing the date field to something you prefer.

**Comment by andy-vdg** [comment]
How about a small update tool that everyone can run their resume through that can correct any required data changes? Should take very little time seeing as ChatGPT exists. Also some documentation on breaking changes would be awesome.

**Comment by souliane** [comment]
I have been impacted by this too, it seems that some dates were not correctly saved in v3 and since v4 now handles them as a free text field, it just displays the whole information. Beside updating them manually on the website, I assume that exporting to JSON, fixing with a text editor and importing back works too.

TBH I really miss the "date format" feature, it was useful to track accurate periods without having to display the day number in my CV. I was really happy with v3 (I discovered the project just a few days before v4) and got surprised by the new version which came with a few breaking changes. Don't get me wrong - thumbs up and many thanks for offering us this great free software and service! Just a prior notice that a big update is coming and might break things would have been nice :-)

**Comment by AmruthPillai** [comment]
I loved the date format feature too, trust me, but it was a double edged sword.

One, some users preferred to have different date format for different sections, showing this field in multiple places in the UI would make it look cluttered. 

But the biggest annoyance of all was how JavaScript (or the web) handles date objects. There was no consistent way to display the correct date time on the resume if people were looking at the same resume across the globe. 

Honestly, as much as I loved the feature, it's probably not the best use case to use date objects in a resume since there's no data being analysed here or data manipulation. Free text fields allow the user to not only enter dates, but anything they want (like period of years and months at a job).
