### ISSUE TITLE
[Bug] LinkedIn import fails

### ISSUE THREAD

**Issue by thepaperpilot** [AmruthPillai/Reactive-Resume#1604]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

I exported my LinkedIn data (all of it) and tried importing it, and got a "Oops, the server returned an error." toast. I got the same on the cloud app as well. Best I can tell, based off the docs, I think the issue would be my zip file not having a Certifications or Projects csv file. I don't see any errors in the console nor the docker container's logs.

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

None

**Comment by CartCaved** [comment]
I see the same issue using Firefox.

Pressing Validate gives no error, but when pressing import, the oops message is shows.

I added the two missing sections (projects and certificates) in my linkedin profile and requested a new archive. This time I got an error at validation due to the certificate not having a valid URL (this is not a required field in LinkedIn).

I added a URL in the csv and tried again. At this point the same error as above occured, validation passes but import fails with an oops message.

**Comment by AmruthPillai** [comment]
Even if the zip archive doesn't have one of those files, it should work. I'm surprised that there's an error being thrown because of this.

The issue here is I didn't really test it out with any other LinkedIn Export except my own, so I don't know all the edge cases that could occur.

If you are okay with sharing your data with me, please send your LinkedIn data export zip archive (as-is, with no modifications) to my email hello@amruthpillai.com and I'll take a look asap.

**Comment by AndreaPi** [comment]
Hi @AmruthPillai, I'm having the same issue as @thepaperpilot

**Comment by jonwtech** [comment]
Hello, I'm also experiencing this error. I am a bit stuck since the migration to v4 since the custom sections of my existing resume have disappeared (https://github.com/AmruthPillai/Reactive-Resume/issues/1613) and I can't start again from a fresh import due to this issue.

**Comment by Snapicek** [comment]
Same issue - try on https://rxresu.me/ - firstly there came error of file Certification.csv - there were invalid url or no url - removed manually. Then upload again, it was validated. After clicking on Import - the error of "Ooops, the server returned an error."

**Comment by DM1122** [comment]
> I was having a similar issue and believe it could be due to missing values in the csv file(s).
> 
> In my `profile.csv` file, the second line had something like this:
> 
> ```
> FirstName,LastName,,,,Software Engineer at XYZ Corp,"My description is here",Software Development,90210,"A City, State, Country",,[PERSONAL:mywebsite.com],
> ```
> 
> In the above there are some missing required values found in the `profile.ts` schema found [here](https://github.com/AmruthPillai/Reactive-Resume/blob/main/libs/parser/src/linkedin/schema/profile.ts)
> 
> Filling in those values with mock data (such as the word "test") fixes the issue. Updating the `profile.ts` schema to have optional will probably fix this issue. For instance, I don't provide an address or birth date which are required fields.

This worked for me. It was the Twitter handle that I had not set on my LinkedIn but which was required by the `profile.ts` schema that was causing the "Oops, the server returned an error". I populated that field in the `profile.csv` using `test`. 

I also had to insert mock URLs into the `Certifications.csv` `Url` column (i.e. `http://www.example.com`) to get past the initial validation errors.

**Comment by AndreaPi** [comment]
@AmruthPillai when do you think this could be fixed? It's really impacting the usability of an otherwise amazing tool. Thanks, and Happy New Year!

**Comment by SergejKasper** [comment]
There are actually two issues:
1. [profile.Websites ](https://github.com/AmruthPillai/Reactive-Resume/pull/1717/files#diff-210ca75852b191fbe6345d3e7308e336d88642f44fb5e3c30de9bbc6ef704218L67) is an array like structure like `[COMPANY:https://some.link,PORTFOLIO:...]` because you can provide multiple links on LinkedIn 
2. The user might not have a Twitter profile and thus [twitterHandle](https://github.com/AmruthPillai/Reactive-Resume/pull/1717/files#diff-210ca75852b191fbe6345d3e7308e336d88642f44fb5e3c30de9bbc6ef704218R72) may not be around
