### ISSUE TITLE
Support for https://jsonresume.org/schema/ 

### ISSUE THREAD

**Issue by T-h-o-m-a-s** [AmruthPillai/Reactive-Resume#162]
It would be nice with support for jsonresume import/export format.

https://jsonresume.org/schema/

**Comment by rowe-morehouse** [comment]
Totally agree. I thought the JSON export would be following the widely accepted and used `json resume schema` mentioned by @T-h-o-m-a-s in this thread. I'd say this is a "must have, rather than a "nice to have." 

Besides that, this is a REALLY slick app. @AmruthPillai, you are very good at product design! :)

**Comment by rrjanbiah** [comment]
FWIW, since @SHENG-X is super active, this feature may be of interest to you.

**Comment by SHENG-X** [comment]
@rrjanbiah I am interested in implement this feature, but it will take a while for me to get there. I did not see the project owner's activities for a few days, so I decided to use this project as a base to build my own resume builder with more features. Check out my latest branch to see what I did if you have time. https://github.com/SHENG-X/Reactive-Resume (branch name: develop-canadian-resume)

**Comment by rrjanbiah** [comment]
@SHENG-X Sure!

**Comment by rrjanbiah** [comment]
@SHENG-X Please also consider hosting it somewhere, at least in github pages

**Comment by SHENG-X** [comment]
Thanks, @rrjanbiah. The latest of my application is temporally hosted at http://159.203.38.171:5000/

**Comment by rrjanbiah** [comment]
@SHENG-X Nice UI approach. Looks like you've also modified the template look and feel. FWIW, I'm adding screenshots of @AmruthPillai and @SHENG-X in case if the server goes down:

## @AmruthPillai
Options in both side

![screencapture-rx-resume-web-app-2020-06-12-23_11_13](https://user-images.githubusercontent.com/4907427/84531736-a51e7d00-ad02-11ea-8711-c7e545d1bff4.png)

## @SHENG-X fork

From left to right UI. Also, some changes in the template

![screencapture-159-203-38-171-5000-2020-06-12-23_12_18](https://user-images.githubusercontent.com/4907427/84531858-da2acf80-ad02-11ea-9b12-acd9e30bdc8f.png)

**Comment by AmruthPillai** [comment]
@SHENG-X This is really good, I love the direction in which you've taken the UI. It's much more sleek and gives more focus to the artboard than just the tabs.

I haven't been able to tend to this project as much as I used to mainly because I have recently been employed at @postmanlabs. But I'll soon get back to this and revamp the idea from ground up to allow more users to contribute (in terms of code and resume templates) and the most obvious feature of all, importing data from JSONResume.org schemas. 

I'm blessed to know that there are active members like you in the community who are willing to contribute to Reactive Resume even in my temporary absence. If you feel your change is good enough for implementation, do raise a PR from your branch to my develop, will have it merged as soon as I can.

Thank you so much, everyone, for your never-ending support!

**Comment by AmruthPillai** [comment]
Closing this issue as Reactive Resume has been bumped up to v2.
