### ISSUE TITLE
PDF Generation: Resume is always saved as a single page file, hence the entire resume is printed in same page and the PDF file is not useful for printing

### ISSUE THREAD

**Issue by everinox** [AmruthPillai/Reactive-Resume#1765]
### Is there an existing issue for this feature?

- [X] Yes, I have searched the existing issues and it doesn't exist.

### Feature Description

Whenever I save a resume document as PDF file, the whole document is saved as a single page. Due to this, recruiters are not able print the document while try are trying to print a hard-copy before the interview.

Please let me know, if there are any workaround or is it an accepted drawback? 

Thanks,
LG

**Comment by AmruthPillai** [comment]
Please refer to this doc explaining how you can create multi-page resumes:
https://docs.rxresu.me/product-guides/creating-a-multi-page-resume

**Comment by everinox** [comment]
Thank you so much Amruth Pillai.
It was really helpful and your work is really appreciated.

Thanks,
LG

**Comment by TimPasquini** [comment]
> Please refer to this doc explaining how you can create multi-page resumes: https://docs.rxresu.me/product-guides/creating-a-multi-page-resume

I'm not sure this actually solves the issue since individual sections cannot be on more than 1 page. If you have a particularly long experience block, for example, you just end up with a good page 1 and a page 2 that still looks terrible.

As a hacky worka-around, I only use my current job in the "Experience" block and have created custom sections with blank names for each previous job. This allows me to arrange the jobs individually and have experience correctly split between more than 1 paper page.
