### ISSUE TITLE
How can I run production

### ISSUE THREAD

**Issue by HungFpoly** [AmruthPillai/Reactive-Resume#1806]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Cloud (http://rxresu.me)

### Current Behavior

I have been able to run development but now I have deployed this project to digitalocean, here is the link: https://app.cveuropass.eu/
but now I have an error that I can't upload avatars and download cvs.
Please help me.
![image_2024_03_11T06_08_10_185Z](https://github.com/AmruthPillai/Reactive-Resume/assets/70883077/e33f191e-f948-4e0e-a40d-7bcc0410cc6e)

### What template are you using?

None

**Comment by AmruthPillai** [comment]
Do you have any error logs that can help me understand what the issue is here?

The image does look like it got uploaded to the storage bucket because of the generated URL, but for it to display correctly, maybe the storage bucket is not set to public, to allow anyone to access the files through a link?

**Comment by HungFpoly** [comment]
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/70883077/98d9efe1-9242-4b5f-9e30-b3af6391aee1)
I got this error when downloading my cv. Can anyone help me?
