### ISSUE TITLE
Resume Download issue

### ISSUE THREAD

**Issue by tcastel94** [AmruthPillai/Reactive-Resume#1821]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

When i want to download my resume, nothing is happening...

### Steps To Reproduce

click on pdf download on the footer or on the right side

### What browsers are you seeing the problem on?

Chrome

### What template are you using?

Pikachu

**Comment by AmruthPillai** [comment]
The server has crashed due to over-use, it has maxed out all CPU, RAM availability so the Docker Stack was stuck in a restart loop.

Please give it a while for it to recoup. Unfortunately, there's nothing I can do to solve this except pour more money into the servers to get a bigger one.

**Comment by andrew-cullen** [comment]
Hi - AmruthPillai, the issue raised by tcastel94 seemed to specifically relate to the self-hosted version, rather than your hosted version. I can also report experiencing the same issue. 

Unless pdf rendering is not handled by the self-hosted service and is actually being sent back to your centralised server? In which case that would seem to be against the ethos of self-hosting the package in the first place?
