### ISSUE TITLE
[Bug] Inputting OpenAI API key throws weird error

### ISSUE THREAD

**Issue by nate235** [AmruthPillai/Reactive-Resume#1900]
### Is there an existing issue for this?

- [X] Yes, I have searched the existing issues and none of them match my problem.

### Product Variant

Self-Hosted

### Current Behavior

Inputting the API key into the relevant field throws an error, I assume, as API Key turns red and random red character appear below the input field "WtwH+r" (???) . This then triggers another error, I've never seen before triggers, saying chrome is unreachable (screenshotted). App behaves as expected beyond this. Took a long time to get RxV4 working so bummer to now deal with this when I get access to OpenAI.

### Expected Behavior

Entering the OpenAI API key works as suggested by the app.

### What browsers are you seeing the problem on?

Firefox

### What template are you using?

Azurill

### Anything else?

![api](https://github.com/AmruthPillai/Reactive-Resume/assets/26520481/b0a8cfc8-376b-4afb-99ed-d016fd6e9fa1)
![chrome](https://github.com/AmruthPillai/Reactive-Resume/assets/26520481/7143b99d-1131-4da6-a590-a115b4f8ddc0)

Chrome log:

![chromelog](https://github.com/AmruthPillai/Reactive-Resume/assets/26520481/d9032790-3c9c-4de2-9e37-0f8a5e597492)

**Comment by pelicangris** [comment]
Hi,
I have a similar issue where i can not store my OpenAI Key:
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/4183405/57793236-221e-4054-8f88-f8464055c4ba)

I am using the latest version of rxresume which is self hosted using docker.

**Comment by hnk** [comment]
I was running into this issue myself but believe to have found the root cause:

OpenAI is replacing _user_ API keys with _project_ API keys:
<img width="866" alt="openai_user_api_keys" src="https://github.com/AmruthPillai/Reactive-Resume/assets/1783602/4e431c29-fb0f-4020-b3a7-b90a4b831a28">

User API keys follow the format `sk-xxxx...` whereas Project API keys are formatted `sk-proj-xxxx...`.

My guess is that the validator for the input field does not accept that new format. When I paste a _user_ API key into that field, it works as expected.

I expect the form validation to fail, because the regex check fails in [/dashboard/settings/_sections
/openai.tsx](https://github.com/AmruthPillai/Reactive-Resume/blob/3f29ca3add76eada31db485ffb26dc205a6ba137/apps/client/src/pages/dashboard/settings/_sections/openai.tsx#L25).

**Comment by lgwapnitsky** [comment]
this is occurring on the publicly hosted version as well

**Comment by IXEguy** [comment]
Confirmed that this is only happening with the new `proj` type keys @hnk mentioned above.

I generated a legacy key and I no longer get the `WtwH+r` error when I click on the Store Locally button.

**Comment by JackTheTripperr** [comment]
A quick visual guide for users trying to solve this issue:

1. Log into platform.openai.com and click on "API Keys" in the menu on the lefthand side of the screen.

![00](https://github.com/AmruthPillai/Reactive-Resume/assets/130310709/d02f3ad6-0dc8-45fb-9347-8692c9a527e6)


2. In the top right corner of the screen, click "View User API Keys"

![01](https://github.com/AmruthPillai/Reactive-Resume/assets/130310709/84440ed2-9b10-4a78-b572-fbaad06d6fce)


3. Click on "Create New Secret Key"

![02](https://github.com/AmruthPillai/Reactive-Resume/assets/130310709/d43f385a-7421-4cf2-a25f-40b6928a8532)


4. Name your key and click "Create secret key"

![03](https://github.com/AmruthPillai/Reactive-Resume/assets/130310709/0d5a6053-525e-4eaf-8b10-ec4701c0c1ad)


5. Click on "Copy" (you need to copy this key right now, you won't been shown it again) and input this key in the settings of Reactive Resume. You'll know you are using the correct key because it will start with "sk-xxxx" instead of sk-proj-xxxx"

![04](https://github.com/AmruthPillai/Reactive-Resume/assets/130310709/7181b772-55f3-4080-8f04-1058c2ae0078)


6. The error should no longer be present when entering the key.

**Comment by frankja2** [comment]
@JackTheTripperr 
> A quick visual guide for users trying to solve this issue:

it doesn't work. When I generate a key it always starts with sk-proj-xxx

**Comment by ChristopheAwad** [comment]
I think this may need to be reopened, as OpenAI no longer allows the creation of user API Keys.
