### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by YR3** [AmruthPillai/Reactive-Resume#2046]

**Comment by sonatuzun** [comment]
@AmruthPillai This project is fire 🔥dude was helping me and people around me for years now. Don't let idiots like this demotivate you

**Comment by Dracco61** [comment]
You sound incredibly upset about wasting your time on something when you could have just stopped using it. Please just provide good feedback instead of ranting about how you're not having the experience you want. I'm sorry but all of this just comes off as a waste of a post to the rest of us.

In the meantime kudos to @AmruthPillai, I really like this project. Been wanting a resume builder for a long time.

**Comment by BNolet** [comment]
@YR3 Looking at how your contributions mostly dropped off somewhere in May I would say that you need to either seek professional help or reach out to some friends for support. 

The feedback given here could have been said in far less words and in a much more productive way. You're doing nothing here but tearing down someone for the sake of wanting credit for their work and wanting to be the steward of their own project. 

If you don't like the way things are done in the project, then go fork it yourself.

**Comment by danilomo** [comment]
Mãe, eu tô no print!!!!!
