### ISSUE TITLE
[Feature] Export html

### ISSUE THREAD

**Issue by smkplus** [AmruthPillai/Reactive-Resume#23]
can you add an option to export html?
I want to change html tags manually

**Comment by AmruthPillai** [comment]
I'm afraid I don't quite know how this can be implemented. Since the project is in React + Tailwind CSS and the templates are heavily dependent on the two for functionality, it is not possible to easily make an HTML copy of the same. I can't seem to find any Shadow DOM Object to HTML Converter either to make this process easier.

If you or anyone has any suggestions, please let us know, will keep the issue open for a short period of time. Thank you for your feedback.

**Comment by smkplus** [comment]
ok instead of exporting html please add export to Microsoft Word
because I like a editable resume

**Comment by AmruthPillai** [comment]
Extracting it to Microsoft Word would make your resume a byproduct, as in, whatever changes you make on the Word Doc, you would not be able to import back into the app. If you feel like there's something that you are not able to edit on the app itself, do let me know, we'll try to figure out a way on how to do that instead :)

**Comment by smkplus** [comment]
your tabs are statics
I couldn't add custom tap like
![image](https://user-images.githubusercontent.com/16706911/77909490-b4b12c80-72a2-11ea-9c8e-dedebbcdc5cc.png)
Interpersonal Skills
Other Skills
Tools & Technologies
