### ISSUE TITLE
Data encryption

### ISSUE THREAD

**Issue by Chuhtra** [AmruthPillai/Reactive-Resume#269]
Hello, 

I wanted to ask if the data that are collected/stored for Reactive-Resume (like mentioned [here](https://rxresu.me/faq)) are encrypted. 

If they aren't, I would like for this to be considered a feature request.

This is a great FOSS product, thank you!

**Comment by AmruthPillai** [comment]
I'd love to, I really would. But it would change a lot of the logic I have already, and while that it is possible, it would be difficult for me to work on right now with my full time job. But I definitely do like the idea of encrypting all the data, something that should have been there in the initial release, but since the data is mostly just going to sit in cold storage with no eyes peeking through it, I didn't work on it.

The main issue here is how to make sure all users are migrated to encrypted resumes at the same time so nobody loses access? Any ideas?

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
