### ISSUE TITLE
Online resume parser Cannot read my resume

### ISSUE THREAD

**Issue by mksphaninder** [AmruthPillai/Reactive-Resume#293]
This is a great tool to develop the resume but, whenever I upload my resume. I am having a tough time getting the ATS to read my system. It would be great if the text in the resume could be copyable.

**Comment by DarshanGowda0** [comment]
I face the same issue with the Pikachu template. 
Parsing problems for me are mainly because the other skills and languages start creeping into the middle of the work experience and education section.
I think this could be solved if the main content is on the left side and the other skills on right!

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
