### ISSUE TITLE
Photo formatting and PDF printing

### ISSUE THREAD

**Issue by dawit8** [AmruthPillai/Reactive-Resume#31]
Hi! 

Thanks for developing this innovative and incredibly useful resource for us all ... for free!! I really want to thank you for your work and creativity! 

Issue #1: I've noticed the photo formatting is a little off. It seems like it's stretched sideways. 
Issue #2: When printing the document to a PDF, the formatting is not as crisp as the web page, and it bleeds into a second page unexpectedly. So, maybe it would be nice to limit the template to fit a page size (US Letter, A4, etc). 

Thanks again for your great work!

**Comment by AmruthPillai** [comment]
Hey there :)

Regarding the first issue, it is actually only visible in the preview mode of the app because we're using a CSS property called `zoom` that still has a few kinks in it with regards to browsers. But this issue will not be visible in the final print version or the PDF of the resume.

About the second issue, I haven't had any issues regarding the quality of the PDF. It prints everything into a vectorized format so it should be visible. Maybe it's an issue with the browser? I have tried it on Chrome and Safari and it works well.

I'm currently looking into some solutions where the PDF is built internally and not through the browser. Will do my best to keep you updated on that. Thank you so much for the feedback :)

**Comment by AmruthPillai** [comment]
Merged into #41
