### ISSUE TITLE
[Feature] Guidelines for template request

### ISSUE THREAD

**Issue by EmaSuriano** [AmruthPillai/Reactive-Resume#33]
Hey, amazing project! I really liked it. I was wondering in case I want to create my own template, is there any guideline that I need to follow or something? 

Thanks for open sourcing this :)

**Comment by AmruthPillai** [comment]
Hey there, thank you so much :)

Currently, building your own template would be a bit of a hassle. There are too many things flying around and there are new features being added day in and day out, that's why I haven't written a guide on doing that yet. Maybe in some time, will definitely write a tutorial on making your own templates and submitting them. It's not tough, it's just a lot of repetitive copy-pasting of the original templates and making slight adjustments to design.

**Comment by nmcc1212** [comment]
Hi @AmruthPillai, love the project!, any chance there is an update on this process?
