### ISSUE TITLE
[Feature] Reoganize resume sections

### ISSUE THREAD

**Issue by loudjanilef** [AmruthPillai/Reactive-Resume#40]
First of all, thank you very much for your project, this is a great work.

**Is your feature request related to a problem? Please describe.**
As a young developer, my education is more important than my work experience. Therefore, displaying my work experience before my education is not very interesting.

**Describe the solution you'd like**
I would like to be able to choose the order of the sections (or at least those two).

**Describe alternatives you've considered**
Another solution would be to write another template with this section order, but this would limit the personalisation possibilities of the app.

**Comment by AmruthPillai** [comment]
This is a lot more difficult than it seems to implement, especially given the current structure of the JSON. I would have to rewrite the JSON structure and also the way templates are passing the JSON. Once I am clear on how to approach this issue, I'll definitely get it done. Thank you for your feedback and patience :)

@loudjanilef As a workaround in your case, it might not be the same thing, but you could rename the Work Experience tab to Education and put in all your details there. The layout doesn't change much since there is almost the same number of fields. It might look off for a bit, but once you're done with your resume, it will look the way it is supposed to :)

**Comment by loudjanilef** [comment]
I understand, thank you for giving an eye, I'll try this 😄
