### ISSUE TITLE
Full name font size changes after exporting

### ISSUE THREAD

**Issue by 4shutosh** [AmruthPillai/Reactive-Resume#419]
Full name size changes after exporting. 
The full name size is visible in proper size in the webview but is turned to small after exporting.

**Webview:** 
![image](https://user-images.githubusercontent.com/53831987/103555950-0e502280-4ed7-11eb-88d4-854ede54dd3a.png)

In **PDF** :
![image](https://user-images.githubusercontent.com/53831987/103556062-32abff00-4ed7-11eb-86ec-768e54181634.png)

**Comment by 4shutosh** [comment]
@AmruthPillai Please take a look.
Can this issue be given the highest priority for now?

**Comment by marinang** [comment]
A bit of a different problem but because of the font size my email is split across two lines ...

![image](https://user-images.githubusercontent.com/24250309/103649741-4733da00-4f5f-11eb-95d1-a83e2e48f6c2.png)

Adjusting the font size on the app solves this problem but it is still exported in pdf with a somehow default font size.

**Comment by AmruthPillai** [comment]
Taking a look at it now... introducing new features almost always tends to crop up new issues.

**Comment by AmruthPillai** [comment]
This has been fixed in v2.5.2 :)

**Comment by 4shutosh** [comment]
Thank you @AmruthPillai . Great Work!
