### ISSUE TITLE
A quick guide to add new templates.

### ISSUE THREAD

**Issue by vijay-yadav-3** [AmruthPillai/Reactive-Resume#420]
I would like to add new templates to the app. From what I believe I have to add mytemplate.js file in src/templates and make use of blocks avilable in src/templates/blocks or create new blocks type if required (contactE,F,G..).
Add a mytemplate.png file in static/images/templates/.
Is there anything else needed to be done for creating my own template. If yes can you give a quick guide file.

**Comment by AmruthPillai** [comment]
You got the basic understanding right. There's not really much to it. I've tried to make it as modular as possible with the blocks concept so there would be very little work to be re-done. For styling, I've made use of Tailwind CSS, would be great if you can use that too but I won't hold you against it. You can alternatively create a new modular CSS file within the same location.

It's just a lot of trial and error, but you'll get there in no time. I do want to be able to add more templates to it, but designing is a time-consuming process and I just don't seem to have any of it since the new job. Do let me know how it works for you, and if you have any specific questions, will keep this issue open so we can discuss :)

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
