### ISSUE TITLE
[Discussion] Thinking of adding non-intrusive advertising to help pay for growing server costs

### ISSUE THREAD

**Issue by AmruthPillai** [AmruthPillai/Reactive-Resume#457]
I've been thinking of adding ads on the platform to pay for server/hosting costs (just one block, which follows app theme), as the traffic keeps increasing to rate in which the cloud bills just keep getting higher. Donations are great, and I appreciate everyone's contribution, big or small, but the demand is just too high to keep up with supply :(

I'm open to hearing any suggestions/thoughts from the community.
Would this be a welcome change?

**Comment by mlow** [comment]
I'd say go for it! You've created something very useful to many and are already sharing the code for it. If someone is bothered by the ads, they have the option of self-hosting :)

**Comment by LavenderServer** [comment]
It's been a while since I've been here, but I'm curious. Will this increase tracking/trackers in the site? If so, by how much? If  the site has little to no tracking and the ads don't intrude with the user's experience, then I'm fine with it.

Have you ever thought about sponsors? Maybe that can help with the cloud costs. You can put a small section in the homepage like how [privacytools.io does it](https://www.privacytools.io/)

**Comment by AmruthPillai** [comment]
@mlow Thank you for the kind words, and I also noticed that you donated on [BuyMeACoffee](https://www.buymeacoffee.com/AmruthPillai). Thank you so much for that, only moves us closer to a stage where we never need to depend on advertising ever. It's truly appreciated.

@LavenderServer That's actually a very interesting idea. I didn't think of that, going with site sponsors instead of ads that track. But I think the main difficulty there is finding websites that want to sponsor on the site, and the initial push to reach out to other site admins. But definitely going to prioritise this over using CPC ad agencies AdSense or Media.net. Thank you so much!

**Comment by LavenderServer** [comment]
@AmruthPillai  If you aren't able to get a sponsor, you can consider what Ad model will used on the site. I'm no expert but it can be done in various ways. Although @mlow did give a good point, let's assume that self-hosting isn't an option. 


### Model 1: Everyone gets ads, but it will not be intrusive. 
Pros:
- It will easily visible but won't interfere with the site's usability. 
- Easiest option since certain services already provide these tools. 

Cons:
- Possible reduction of users due to dislike of ads and trackers.

Things that needs to be considered:
Advertising Agency (Which is best for the site?)
Position and size of ads
The quantity of ads





### Model 2:  Site has ads, but users can subscribe to remove this. 
Pros:
- Give the users the chance to choose. Either use the free service with ads or subscribe to remove it. 
- Site can be continually supported while still providing the basic features to all users. 

Cons:
- Requires more resources than Model 1
- Requires a system that processes and monitors payments effectively
- Requires more security monitoring.

Things that need to be considered:
The cost of the subscription
Payment plan (monthly or yearly?)
Services chosen to monitor and process payments
How to ensure security in payments and in user accounts?


Now, this is just a simple draft. With time, things can be changed or added. The idea is to evaluate the options and find a solution.

**Comment by gianantoniopini** [comment]
Another option which could be considered is to have two plans: Free and Paid.

The **Free plan** is for users who just want the basic functionality and/or are not able to pay for the more advanced features. This plan will have some limitations which will need to be defined. Possible examples of limitations: limit on number of resumes, limited set of templates that can be used. Possible example of advanced feature not available under this plan: import resume. This Free plan would be supported through the Paid plan.
The **Paid plan** is for professional users who want the basic functionality plus all the more advanced features and are able to pay a monthly/yearly subscription fee. The Paid plan will not have any limitations.

Users on the Free plan would be able to upgrade to Paid plan. And vice versa: users on the Paid plan would be able to downgrade to Free plan.

In both plans there will be no ads.

**Comment by LavenderServer** [comment]
@gianantoniopini 
Not a bad idea. Let's see how it goes. 😁

**Comment by Skyclo** [comment]
Look into [Fosshost](https://fosshost.org/). They might be able to help you guys out a bit.

**Comment by AmruthPillai** [comment]
Closing this in favor of Reactive Resume v3 release.
If you continue to face this issue, please raise a new one and I'll have a look at it as soon as I can.

In the meantime, if you are able to, please consider donating to keep supporting the project: https://www.buymeacoffee.com/AmruthPillai :)

Thank you!
