### ISSUE TITLE
Resume still viewable & public even if the account is deleted 

### ISSUE THREAD

**Issue by vaib25vicky** [AmruthPillai/Reactive-Resume#466]
Hi,

I believed the same concern was raised in the past https://github.com/AmruthPillai/Reactive-Resume/issues/253

This is still not fixed, I've tested only with anonymous login. The steps to reproduce are same.

Proof of concept:

The account with ID fqwtkm has been deleted but the resume is still viewable and public

https://rxresu.me/r/fqwtkm

Thank you!

**Comment by AmruthPillai** [comment]
Will look into this. I believe this issue is with the cloud function itself, where I'm trying to delete all resumes (https://github.com/AmruthPillai/Reactive-Resume/blob/develop/functions/index.js). Instead of using a forEach array, refactoring it to a Promise.all array should help.

Thank you for bringing this to light, will raise a PR fixing this as soon as I get the time :)

**Comment by gianantoniopini** [comment]
@AmruthPillai Hi Amruth, in case you are short of time, I would be happy to help with this.

**Comment by AmruthPillai** [comment]
@gianantoniopini That would be very helpful, thank you!

**Comment by gianantoniopini** [comment]
You are welcome! I will try to reproduce the issue and debug/test the cloud function. Hopefully I can raise a PR soon.
