### ISSUE TITLE
The export function could not adjust the margins

### ISSUE THREAD

**Issue by wangqinggang** [AmruthPillai/Reactive-Resume#55]
- There is a blank margins when exporting your resume.

- it is not very comfortable when zoom in and out.

I love this software so much, I deployed it the first time I found it, thank you so much. I hope I can provide Chinese help for the software and documentation.

**Comment by AmruthPillai** [comment]
The blank margins, they appear when you export the resume? Can you please give me a few more details such as which theme, which browser?

As for the zoom issue, I've noticed that the zoom is a bit laggy on Firefox, but works well on Chrome/Safari. I'm yet to find a solution to FF, are you a Firefox user as well or is this happening to you on some other browser?

Thank you so much for the feedback, for the comments :) It really means a lot. Someone has already helped out with translating the app to Chinese, but you can try using the app and seeing if there are any mistakes. Please do share it with as many people as you can. The more people this can help, the better, especially during a time when there's going to be a gold rush for jobs. I hope everything is safe wherever you are. Do take care, and thank you so much.

**Comment by qiandongyq** [comment]
Maybe this? It loos like happen on both chrome and firefox on all templates. Just some templates have white space on both sides by default, so it not look that obviously.
![image](https://user-images.githubusercontent.com/24208956/78200832-d7d40b80-745d-11ea-8d45-63b75c59cfbf.png)

**Comment by AmruthPillai** [comment]
Thank you so much @qiandongyq, for this and all the contribution you've been doing around Reactive Resume. It is truly appreciated and I am very very thankful for that. 

If this is the margins issue people are talking about, then this is expected behaviour. What happens is, the page is actually longer than it is supposed to be, so to fit it inside an A4 paper, it scales itself down and it is centred. By default, it is left-aligned but I made it to centre to the page. If you feel this behaviour is not right and it should be left-aligned instead, that can be arranged.

**Comment by AmruthPillai** [comment]
This has been resolved with the push of #66, thanks everyone :)
