### ISSUE TITLE
[Bug] Links aren't clickable, text isn't selectable.

### ISSUE THREAD

**Issue by dw-ll** [AmruthPillai/Reactive-Resume#61]
This project is great, came across it this morning and have since created a beautiful resume. One thing I noticed though is my website link or any links I list using markdown cannot be clicked once I have exported to PDF. The same goes for selecting any of the text on the actual PDF, I can imagine this might be detrimental when your resume is being parsed by an employer, is there something I'm missing here?

**Comment by qiandongyq** [comment]
This is not a bug. The resume is actually exported as an image embed into Pdf. That's the reason you can not select any text and links will not be working.

**Comment by AmruthPillai** [comment]
@qiandongyq You are absolutely right. We were using the original browser printing method before, but as it turns out, it caused a lot more problems than it was trying to solve. The results varied from browser to browser and there was a lot of issues with getting the entire resume on one page.

Since then, we've moved to the new method where we generate PDFs through built-in libraries. This does make the links not clickable again, but I feel that is a small price to pay for the ability to get a properly printed one-page resume. I'll definitely look into what I can do to get both the browser print functionality and this generation method to run side by side.

Thank you for your feedback, support and patience :) It is very much appreciated.

**Comment by barisdemiray** [comment]
Hey Amruth, thanks a lot for creating such a great tool. I understand the technical reasons behind it but could you keep this bug open especially since you said you'd look into it, please? Not having text functionality on such a great output (again.. which is great because it's sadly an image and not a text-based document) is a shame.

**Comment by AmruthPillai** [comment]
Hey @barisdemiray!

Actually, the browser print functionality was brought back. I'm sorry, my mistake for not having updated the issue, but there were just so many 🙈 If you were to print the resume, by using Cmd/Ctrl + P instead of using the PDF Export method, you would get a text selectable version of the resume as well as links being clickable on PDF readers like Adobe.

The only issue with it is, it works best only on One Page Resumes, with multiple it's a hit/miss, not that it won't work well. And it is tested to work best only on Google Chrome (or other Chromium browsers). Firefox gives me a hard time.

**Comment by barisdemiray** [comment]
Hey @AmruthPillai ! Thanks a lot for the response. Finally I figured it out and by playing with the margins and the layout, I managed to print my 3-page CV nicely to PDF. Yet it's not something reusable because it's dependent on the length of certificates section, etc. So no pull request for the moment. When I have time I'll happily contribute.
