### ISSUE TITLE
 [i18n] Date translation

### ISSUE THREAD

**Issue by nathanaelhoun** [AmruthPillai/Reactive-Resume#665]
As asked in #581 before v3 release, it would be great to translate dates (for example, in French, "August 31, 2021" is « 31 août 2021 »).

Everything else is translatable, and it makes this software wonderful :-)

**Comment by nathanaelhoun** [comment]
Nevermind, this already exists :facepalm: It's only that French translation is missing, will contribute to add it :-)
![image](https://user-images.githubusercontent.com/45119518/158028672-b7e829fd-c317-4598-8f06-50089ebe34c3.png)

**Comment by AmruthPillai** [comment]
Thank you so much for reporting this, and finding out a solution yourself @nathanaelhoun! Please, I would be more than happy to invite more translators and languages into the app. The dates also should be automatically translated as soon as the locale is activated.

To add a translation, just head on over to https://translate.rxresu.me, create an account and start translating. The Crowdin TM platform is great for quick and easy translations. Do remind me once you're done so that I can add it to the project :)

**Comment by nathanaelhoun** [comment]
Hi @AmruthPillai! Crowdin is indeed great for translating projects like this one, love it!

French is now 100% translated :wink: Let me know when you add it, I will check the Vercel preview to ensure that all strings are looking fine in context :-)
