### ISSUE TITLE
[FEATURE] Example docker-compose.yml which pulls appropriate containers from Docker Hub itself or Github's container repositories.

### ISSUE THREAD

**Issue by Leopere** [AmruthPillai/Reactive-Resume#666]
**Is your feature request related to a problem? Please describe.**
For the most part, the title should be enough; however, I'd like to know at least in the comments within the example docker-compose.yml file provided in this repository which public container images I can pull directly from to deploy this tool.

**Comment by Leopere** [comment]
Also kudos for using the correct reverse proxy tool with the correct style of configuration <3

**Comment by AmruthPillai** [comment]
Thank you so much for your support to the project by creating issues and asking questions :) Truly appreciate the interactivity. I would like to know a bit more, because as I understand it, the current `docker-compose.yml` already contains comments on which image to pull for production runs.

https://github.com/AmruthPillai/Reactive-Resume/blob/ebd9253038ada5389fff004bcd1d4640a455a404/docker-compose.yml#L28
https://github.com/AmruthPillai/Reactive-Resume/blob/ebd9253038ada5389fff004bcd1d4640a455a404/docker-compose.yml#L52

**Comment by Pheggas** [comment]
Is there finished docker-compose yml file? so everyone with compose can deploy it?

**Comment by AmruthPillai** [comment]
@Pheggas Working on it right now, along with a doc on how to deploy on a server. Will have an update soon :)

**Comment by AmruthPillai** [comment]
I've updated the docker-compose.yml to work right out of the box now. Just ensure to change the `<SERVER-IP>` values within the file to make it work on your server so that you can access it externally on your home network.
