### ISSUE TITLE
[FEATURE] (v2) (v3) Privacy -- Hosting uploaded photos not on Google Firebase, but somewhere more privacy-friendly.

### ISSUE THREAD

**Issue by VanBrugg3n** [AmruthPillai/Reactive-Resume#672]
In version 2, I noticed my uploaded test image's URL to be "firebase.google.something". I'm concerned for my photo being copied, scanned and analyzed by Big Brother G. Is there an option for a more privacy-friendly hosting?

**Comment by AmruthPillai** [comment]
That was the limitation with version 2. Which is why I implemented upload on v3, where images are stored on the server's location directly. There is no connection to firebase in v3, so this issue is for V2 only, and mostly a "wontfix" as this was one of the big limitations of the old version that brought on the change.
