### ISSUE TITLE
v3 full of bugs

### ISSUE THREAD

**Issue by gpopesc** [AmruthPillai/Reactive-Resume#679]
1. The resume is not saving: I create a new resume, I filled some data, exit on main page, go back in resume is not saved!!! (workaround fill data, then export export json, them import when you need it back. 
2. to add new page is tricky and not intuitive, there is no option to have multiple pages of work experience
3. in "education" print comma out of blue

4. the print is a totally mess in V2 .

in this moment none of the versions are usable 
please fix them

**Comment by AmruthPillai** [comment]
1. Fixed issue where cache was hit instead of getting latest resume when navigating out and into builder again. Should be resolved in [v3.2.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.2.0).

2. If you could suggest what would be a more intuitive method to add pages, I'm all up for listening. This is what I could come up with. As for having multiple pages of work experience, it is merely up to you to use some creativity/logic. You can create a custom section with the same name "Work Experience" and drag it to the new page to have multiple pages of experiences.

3. Education comma issue is resolved as of v3.2.0.

4. Print functionality in v2 has been fixed.

**Comment by gpopesc** [comment]
>     2. If you could suggest what would be a more intuitive method to add pages, I'm all up for listening. This is what I could come up with. As for having multiple pages of work experience, it is merely up to you to use some creativity/logic. You can create a custom section with the same name "Work Experience" and drag it to the new page to have multiple pages of experiences.

I think you can put page format in settings definition. (A4, letter or one page). Based on this settings the info will spill on multiple pages. As example for work experience, I have about 1,5 pages.
