### ISSUE TITLE
[Feature] Hyperlinks for Names

### ISSUE THREAD

**Issue by felix-seifert** [AmruthPillai/Reactive-Resume#71]
**Is your feature request related to a problem? Please describe.**
HR employees who assess your resume often do not know how to classify different institutions in your CV (e.g. universities, companies). With their limited time per resume, they might go with applicants with well-known names as looking-up every single institution might be too time-consuming.

**Describe the solution you'd like**
A way I usually go is to provide a hyperlink for every employer and university listed in my resume. Like this, readers just have to click on the name of the institution which immediately directs them to the relevant homepage. Additionally, names of services within descriptions of your occupation could be equipped with links: _Develop 'interesting service name'_. A click on 'interesting service name' should result in directing the reader to the homepage of it.

Idea would be to implement a rich text editor for the different resume fields where you could select to implement a link. Furthermore, other functions to highlight text would be available. However, I am not sure whether institution names which are equipped with links should look differently than normal institution names.

Another, possibly slightly easier version would be to allow styling with markdown.

**Comment by AmruthPillai** [comment]
This is quite a good feature, but ever since I've moved from the browser print method to the new method where a PDF is generated on the fly, it does not propagate links (hyperlinks). Nothing is clickable in the final resulting PDF, so this wouldn't be helpful.

I'll be closing this for now, but if in the future we do find a way to make clickable links within the PDF, will reopen this and work on it :) Thank you so much for the feedback and suggestions.
