### ISSUE TITLE
[BUG] Export to PDF with no english dates not working

### ISSUE THREAD

**Issue by git-61734** [AmruthPillai/Reactive-Resume#729]
**Describe the bug**
Export to PDF with no english dates not working.

**To Reproduce**
1. Change language theme (in french, for exemple)
2. Export to PDF.

**Expected behavior**
Dates should be in french.

**Screenshots**
![Screenshot from 2022-03-17 19-05-24](https://user-images.githubusercontent.com/69983224/158868684-8f6e8793-33e8-414e-8a45-a042a70e0616.png)

![Screenshot from 2022-03-17 19-06-00](https://user-images.githubusercontent.com/69983224/158868747-f41887e7-5b22-4c96-b03c-b98c82b612fd.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: v3.2.6

**Comment by AmruthPillai** [comment]
Able to reproduce this issue, working on a fix now :)

**Comment by git-61734** [comment]
Thank you!

**Comment by WORMSTweaker** [comment]
Hello, as of v3.8.4, this issue is still happening, the steps are the same, OS is Linux, Browser is Firefox
In-editor:
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/1344245/5e55e047-bc3f-4d7d-8f30-5447d9d06433)

Exported PDF:
![image](https://github.com/AmruthPillai/Reactive-Resume/assets/1344245/123452d0-e7d0-47dc-9efa-035ab64bde9d)
