### ISSUE TITLE
[Feature] Enable PDF to be searchable

### ISSUE THREAD

**Issue by patrickdes96** [AmruthPillai/Reactive-Resume#80]
When submitting a resume, the resume should be searchable for resume handling systems 

I want it to be searchable through Ctrl + F

I considered using OCR and parsing it separately, but integrating in the app would be better 

I loved the application, UI and templates. Thanks so much!

**Comment by AmruthPillai** [comment]
This feature, while highly requested, is still being researched upon. Right now, with the method I'm using to get the resume, it captures an image of the entire canvas and converts it into a PDF. Currently, I haven't found another way around it, but will definitely be looking out for more alternatives.

**Comment by Ciboulette** [comment]
Hey @AmruthPillai,

You should have a look to: https://react-pdf.org/

**Comment by AmruthPillai** [comment]
@Ciboulette I have seen that, but it has a lot of overhead to it. I would have to change all my templates to work that way, and then see if it works. Maybe I could look into it when I have the time, thank you so much for sharing.

@patrickdes96 Since I merged #102, PDFs are now searchable, selectable and parse-able if you print them through the browser's print functionality. It works best on the latest version of Google Chrome, I've tested it only there, but it should provide you with what you need. Do let me know if that solves your issue.

**Comment by Ciboulette** [comment]
@AmruthPillai What about using a simple serverless function with puppeteer ?

**Comment by AmruthPillai** [comment]
That would make the app not truly local and browser-only. It would mean having to send your data to a server, like a Cloud Function on Firebase. It does sound like an intriguing option, but it defeats the original purpose of keeping the app privacy-friendly. I don't know how many people would like that.

Do you have a lot of experience with puppeteer on node?

**Comment by Ciboulette** [comment]
All right then understood!

@AmruthPillai I have some experience and I am sure it would work :)

**Comment by smortezah** [comment]
Any progress on this?
