### ISSUE TITLE
[FEATURE] Route prefix

### ISSUE THREAD

**Issue by JosephKav** [AmruthPillai/Reactive-Resume#826]
**Is your feature request related to a problem? Please describe.**
I want to run this with a route prefix, e.g. /reactive-resume, so you need to go to http://FQDN/reactive-resume to access the ReactiveResume site. Putting it behind a location in nginx didn't seem to work as the the page would request js etc without the route prefix (http://FQDN/_next/static/...) and so 404.

**Describe the solution you'd like**
Ideally, it would pick up the route prefix from the PUBLIC_URL var.

**Comment by AmruthPillai** [comment]
Technically, this is a NextJS property. I don't have any plans of implementing this as another env var just yet, because the number of vars to set are increasing by the minute.

But if you are building from source, you should be able to set the `basePath` property in `next.config.js`, as described here: https://nextjs.org/docs/api-reference/next.config.js/basepath to change your path prefix.
