### ISSUE TITLE
Privacy of Users.

### ISSUE THREAD

**Issue by EdwardLangdon** [AmruthPillai/Reactive-Resume#838]
How is the Privacy of the users protected ?

How secure and private is the data ?

I would like to have a Detailed answer on this.

**Comment by michael-robbins** [comment]
Can you provide a detailed question? What aspects of privacy are you curious about? Are you asking about the hosted version of the application or if you are self hosting your own? Do you mean is the data encrypted? Have you used the application at all or are you just asking this before understanding how the application works?

**Comment by EdwardLangdon** [comment]
I am curious in all sorts such as How Data is handled, Who have access to it. Are those access logged - For now.

I am asking about the Hosted version. 

Yeah, I mean whethere data is encrypted or not.

No, I haven't used it before. I am asking to understand as you said.

**Comment by AmruthPillai** [comment]
Data is stored on a managed Postgres database that's on the cloud (DigitalOcean). There's no access log, or any kind of logging in place to store sessions so I would have no idea about metrics such as active users etc.

Who has access to the database? Currently, it's set up in such a way that only the server instance has permissions to connect to the DB. I have not whitelisted any other IP, not even mine. But that doesn't mean I don't have access to it, I could if I wanted to but you'd just have to put faith in an unknown random internet avatar that I have no interest in your or anyone else's data :)

The access to the database required a certificate issued by DigitalOcean itself, so the connection is most definitely encrypted, but the data stored on the database is not. The password on the other hand is hashed + salted (which is clear from the code).

Please, shoot any specific questions you may have about the security and privacy of your data. I openly welcome the curiosity. I built this app and also made an effort to allow to self host mainly because I understand the value of user's privacy. Thank you for the question :)

**Comment by EdwardLangdon** [comment]
So, The Official Instance's data is not viewed by anyone ?

**Comment by AmruthPillai** [comment]
@EdwardLangdon Yep, no one can read/write to the main database.

**Comment by EdwardLangdon** [comment]
Thanks, I might look forward to use Reactive-Resume in Future.
