### ISSUE TITLE
[Feature] Password the Web UI

### ISSUE THREAD

**Issue by geekaroni** [AmruthPillai/Reactive-Resume#86]
Is it possible to add a password or authentication for the web ui? Some people are asking me on my blog about this because they want to expose it. I would also recommend support for SSL.

**Comment by akapu1** [comment]
Yes it will be very helpful..

**Comment by AmruthPillai** [comment]
Could I understand more clearly about why a password would be useful? Because as I've mentioned before in the documentation, the data lies in the client's browser. It isn't stored on the server that is hosting the files.

While I do not understand the clear reasoning for wanting a password, I do believe there are ways you can protect the website right now without any change in the code. If you host the app on an Apache Server, you can password protect it by using the `.htpasswd` file. Similarly, you can do the same on Nginx as well. Will share a few links below that might help.

Apache: https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-18-04
Nginx: https://www.tecmint.com/password-protect-web-directories-in-nginx/
Netlify: https://docs.netlify.com/visitor-access/password-protection/

**Comment by dxfan227** [comment]
@AmruthPillai 
Just chiming in with some thoughts.....

I'm not sure of the original posters reasoning, one thing I could think of is the "consumer". While we here all know about the lengths you have gone through to keep things secure, and always on the users browser. I think the "common folk" feel more comfortable when they are asked to login ( with their own username and password) and don't see " not secure" on the top of the web browser when typing into their computer relatively sensitive information ( Names, Addresses, Phone Numbers, etc..etc..) while we know it doesn't do anything, it might make THEM feel more comfortable using this great app.
