### ISSUE TITLE
User image not exported when saved to PDF

### ISSUE THREAD

**Issue by jamesrweb** [AmruthPillai/Reactive-Resume#94]
I tried to download the CV but the user avatar in the opening section was not exported in the PDF.

**Comment by AmruthPillai** [comment]
Could you please share a screenshot of the issue? You said this is happening to you on the Onyx template? I just tried it and it seems to work as expected. What browser are you using?

**Comment by jamesrweb** [comment]
The latest version of chrome at 100% output quality and unconstrained. I see the image in the preview but not the export.

**Comment by patrickdes96** [comment]
I was facing this issue as well, when you use the site through incognito, the pdf prints fine. I'm guessing it may be some setting in the cache?

**Comment by saravana447** [comment]
I also faced this issue. I tried with incognito mode also still pdf doesn't save with profile pic.
Used Template: Pikachu.
Font: Lato

But when I tried with low resolution or compressed picture. It saves successfully.

**Comment by Bisente** [comment]
Same issue here, all templates. Tried the latest Docker container and also the online version at rxresu.me. Also different browsers (Firefox, Chrome, Safari).

**Comment by AmruthPillai** [comment]
@Bisente I am not able to pinpoint as to why this is happening at all. It works well on my systems as well as desktops that I've never opened the app on before. I tried it on all the 3 browsers and I got the right outputs. Can you share the URL of the image you are trying to enter? It has to be a direct link to the image, I've seen users face the same issue before.

**Comment by Bisente** [comment]
Check your email, just sent you a JSON export for you to test. :-)

**Comment by AmruthPillai** [comment]
Huge thanks to @Bisente and his help with sending me his JSON, I have finally been able to diagnose what the issue is, and I'm afraid it's a bit more complicated than the problems I'm used to.

This is the error that I get when I try to export PDFs:
![Screenshot 2020-04-16 at 2 29 33 AM](https://user-images.githubusercontent.com/1134738/79388468-05a36f00-7f8b-11ea-96a4-368d4ddbeda2.png)

This basically means that the image that is being loaded from a cross-origin cross-domain site does not allow **CORS**. This is usually the case with images that are uploaded on S3, Firebase Storage or other cloud services. I hadn't faced this as I was only testing with images uploaded to imgur.com, but this is a big issue indeed.

I will continue to find solutions to fix this issue, I'm trying everything I can to get this resolved. In the meantime, if you do want to find a hack to this and solve it on your own, some suggestions are:
1) Upload the image to another image host, maybe even your own server, or if you don't mind the privacy risk, imgur.com?
2) The other option is to convert your image to Base64 and insert the b64-encoded string instead of the URL itself. The image will export as expected then. Here's a neat website that can help you with the conversion: https://www.base64-image.de/ You need the code that is to be used within <img> elements.

I understand that this is a big inconvenience to everyone, and I'm really trying my best to get this resolved. Sorry about that. I will keep you guys updated on the solution.

Hope you keep using the app, thank you for your patience.

**Comment by AmruthPillai** [comment]
Since #102, there is an option to directly print your resumes using the browser print window. This is a heavily dependent feature on your OS/Browser, and I've seen that it has the best results on the latest version of Google Chrome.

Please do try this option out as well. I am still trying to figure out the CORS issue with images, but it has very little to do with the frontend and more to do with where you upload the images to, allowing Cross-Origin access right from the source. I will keep the issue open for further discussion on what can be done.

**Comment by Bisente** [comment]
Can confirm that the new browser-based print to PDF method works for me. Thanks! In fact, I prefer this output as it's a text PDF (i.e. you can select, copy and paste text from the CV) whereas the JS-produced PDF was an image (no text selection).

As for CORS... makes sense. The whole app works on the browser side, right? No easy way around that then, some users may not be able to disable CORS wherever their images are uploaded, may consider it a security concern, etc. besides making the app no so user friendly as it is now. 

Possible fixes I can think of involve having some small process running server-side to deal with the images:

- Allow users to upload the pictures to the rxresume server (HTTP POST, small server-side process to move them somewhere accessible to the web server). Then the images would be downloaded from the same domain as the JS and CORS would allow that connection.
- Similar idea but still using URLs instead of direct upload: have some server-side process downloading the image from the URL. As CORS is a browser-based thing, a server-side app would have no problems downloading the images. Then the image is accessed from the same rxresume domain as in the previous step.

Hope that helps!

**Comment by jamesrweb** [comment]
Thanks for the feedback @AmruthPillai and to @Bisente for providing the JSON.

I will close the issue for now but it would be good if you could add feedback to the user @AmruthPillai that this occurs.

Any issue should be notified somehow to the user in an accessible manner by using something like [the alert pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#alert).

Better yet and more recommended to do is adding a message under the input with an icon and text like is described in this article on [accessible input error and info text](https://medium.com/pulsar/creating-accessible-input-errors-and-help-text-74c7e00e757a)!
