### ISSUE TITLE
[FEATURE] Pagebreak within a section

### ISSUE THREAD

**Issue by lightningdave** [AmruthPillai/Reactive-Resume#952]
Hi, I am using the tool for the first time.
Loving it.

One thing: if a have more then a few items in a section: say workexperience. 
I would like to spread that section out over multiple pages.
Now it just makes the font really small when I export to pdf and print.

I could not find a way, other than create separate sections for workexperience and determining.
Lining this out is a headache.

Am I using the tool wrong? Or do you recognize this?

Thanks,
Dave

**Comment by AmruthPillai** [comment]
It's really not possible to create individual page breaks within a section. Introducing that feature opened up a lot more issues during my initial development. Instead, that's why you can now create multiple custom sections. As in the example resume, you can use the Work Experience section for your first set of entries and create a new section to push all your other work experiences, and display them in another page. This would be the most optimal solution as you don't have to mess with page breaks in CSS :)
