### ISSUE TITLE
[BUG] 404 Error in Docker-Compose

### ISSUE THREAD

**Issue by julianq** [AmruthPillai/Reactive-Resume#961]
**Describe the bug**
Docker Compose creates containers as expected, but Traefik throws off a 404 error when trying to access.

**Product Flavor**
- [ ] Managed (https://rxresu.me)
- [X] Self Hosted

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox. Chrome
 - Version Latest

**Comment by coderhs** [comment]
@julianq did you try with localhost in the url, it doesn't work unless the hostname matches.

**Comment by julianq** [comment]
@coderhs that did it! thank you. can't register an account now tho?

**Comment by coderhs** [comment]
@coderhs Are you using docker, the docker images are currently down due to `https://docs.rxresu.me/` being down. There is a code in the health_controller that is checking if `https://docs.rxresu.me/` is online.

I currently edited the file inside the docker image to make it work. 

If its the code you might have to pull the latest code and try, as this issue was fixed only 3 days ago in the source code.

**Comment by julianq** [comment]
@coderhs  Thanks for the response, but the issue i'm having is exactly the same as  #752

**Comment by AmruthPillai** [comment]
Fixed in [v3.6.0](https://github.com/AmruthPillai/Reactive-Resume/releases/tag/v3.6.0)
