### ISSUE TITLE
Should Add pictorial feature in the resume 

### ISSUE THREAD

**Issue by sid02official** [AmruthPillai/Reactive-Resume#985]
please add a feature to add pie chart showing various skills and qualities  to make resume , look  more attractive and appealing as shown in the attachment.
![Screenshot 2022-08-27 114714](https://user-images.githubusercontent.com/110686170/187017747-047534b0-1ee0-44bc-9611-83fb0b9361f0.jpg)

secondly add a feature to add a section in the side bar of thee resume as pointed out in resume.
![Screenshot 2022-08-27 114918](https://user-images.githubusercontent.com/110686170/187017799-7ff2869e-2092-4ec8-9240-d2b93fa972a4.jpg)

**Comment by AmruthPillai** [comment]
So, for the first option, it's generally not suggested to add charts or graphs into the resume as they're not easily read by parsers or easily understood by everyone. Skills are better equated with a countable value rather than an uncountable guess of how much an area is shaded. If you'd still like to add a pre-made image of a chart onto your resume, you can embed images with markdown.

As for the second option, you should be able to do this already, by just creating a new section (on the left sidebar) and drag/dropping it to the second column (on the Layout section, of the right sidebar).
