### ISSUE TITLE
[Bug] Ats systems do not understand that this is a cv/resume

### ISSUE THREAD

**Issue by quintess** [AmruthPillai/Reactive-Resume#99]
Hi!
The program exports pdf in the form of a picture, for this reason ats (Applicant Tracking Systems) systems do not understand that this is a cv/resume because can not recognize the text. 
Will you correct this error?

**Comment by AmruthPillai** [comment]
This is mainly due to the current method where we convert the resume into an image and then export it out as a PDF, but now since #102, you can now print the resume using the browser print function which would allow you to generate parse-able resumes.

This is not perfect as it is heavily browser-dependent, but it works best on the latest version of Google Chrome, as per my testing. I hope that helps :)
